export type NavSection = 
  | 'midia' 
  | 'bandeja' 
  | 'agenda' 
  | 'presupuestos' 
  | 'seguimientos' 
  | 'proveedores'
  | 'impacto' 
  | 'configuracion'
  | 'integraciones';

export interface Vehicle {
  id: string;
  plate: string;
  brand: string;
  model: string;
  year: number;
  kilometers: number;
  motorization: string;
  vin?: string;
  lastServiceDate?: string;
  futureRecommendation?: string;
}

export interface Customer {
  id: string;
  name: string;
  phone: string;
  email: string;
  avatarUrl?: string;
  notes?: string;
}

export interface Message {
  id: string;
  channel: 'whatsapp' | 'phone' | 'web' | 'sms';
  sender: 'client' | 'ai' | 'workshop';
  senderName: string;
  content: string;
  timestamp: string;
}

export interface BibendiaUnderstanding {
  wants: string[];
  alreadyKnows: string[];
  missingInfo: string[];
  nextStep: string;
  autoActionNotice?: string;
  confidence?: 'high' | 'needs_confirmation';
  suggestedSlots?: { date: string; time: string; label: string; workload: string }[];
}

export interface Conversation {
  id: string;
  customerId: string;
  vehicleId: string;
  channel: 'whatsapp' | 'phone' | 'web' | 'sms';
  status: 'needs_attention' | 'ai_handling' | 'resolved';
  unread: boolean;
  lastUpdate: string;
  messages: Message[];
  understanding: BibendiaUnderstanding;
}

export interface Appointment {
  id: string;
  customerId: string;
  vehicleId: string;
  serviceName: string;
  estimatedDurationMinutes: number;
  date: string; // YYYY-MM-DD
  time: string; // HH:mm
  status: 'scheduled' | 'in_progress' | 'completed' | 'sent_to_dms';
  assignedMechanic?: 'Jon' | 'Iker';
  aiCreated: boolean;
  workloadLevel?: 'low' | 'medium' | 'high';
  slotQuality?: 'optimal' | 'good' | 'busy';
  completedNotes?: string;
  futureRecommendation?: string;
}

export interface QuoteItem {
  id: string;
  category: 'part' | 'labor';
  description: string;
  quantity: number;
  unitPrice: number;
  total: number;
}

export interface Quote {
  id: string;
  number: string; // e.g. "PRE-2026-084"
  customerId: string;
  vehicleId: string;
  title: string;
  createdDate: string;
  status: 'draft' | 'pending_approval' | 'sent' | 'accepted' | 'rejected';
  items: QuoteItem[];
  subtotal: number;
  tax: number; // 21% IVA
  total: number;
  estimatedLaborHours: number;
  aiRationale: string;
  uncertaintyWarning?: string;
  customerName?: string;
  vehiclePlate?: string;
}

export interface FollowUpOpportunity {
  id: string;
  customerId: string;
  vehicleId: string;
  type: 'unanswered_quote' | 'upcoming_maintenance' | 'recommended_repair' | 'dormant_client';
  title: string;
  description: string;
  daysPending: number;
  potentialValue: number;
  suggestedMessage: string;
  status: 'pending' | 'sent' | 'converted' | 'dismissed';
}

export interface AiImpactLog {
  id: string;
  timestamp: string; // HH:mm or Date string
  title: string;
  details: string;
  category: 'reception' | 'booking' | 'quote' | 'followup' | 'billing';
  timeSavedMinutes: number;
  revenueImpact?: number;
  isRecovery?: boolean; // Only true if generated by follow-up conversion!
}

// ==========================================
// REAL BACKEND CONTRACT INTERFACES (P0.3 / P0.5)
// ==========================================

export interface WorkshopAppointmentResponse {
  id: string;
  tenant_id: string;
  workshop_id: string;
  case_id: string;
  customer_id: string;
  vehicle_id: string;
  service_request: {
    intent?: string;
    symptoms?: string[];
    notes?: string;
    estimated_duration_minutes?: number;
    [key: string]: unknown;
  };
  start_at: string;
  end_at: string;
  status: string;
  confirmation_evidence_ref: string;
  version: number;
  customer_name: string;
  vehicle_plate: string;
}

export interface TenantControlResponse {
  lifecycle: 'provisioning' | 'pilot' | 'active' | 'suspended' | 'deactivated';
  lifecycleUpdatedAt: string | null;
  lifecycleUpdatedBy: { type: string; id: string } | null;
  lifecycleReason: string | null;
  killSwitch: {
    enabled: boolean;
    updatedAt: string | null;
    updatedBy: string | null;
    reason: string | null;
  };
  version: number;
}

export interface OutboxSummaryRow {
  delivery_state: string;
  count: number;
  oldest_at: string | null;
  max_attempts: number;
}

export interface OutboxAttentionRow {
  id: string;
  event_type: string;
  aggregate_type: string;
  aggregate_id: string;
  delivery_state: string;
  occurred_at: string;
  attempts: number;
  max_attempts: number;
  next_attempt_at: string | null;
  lease_until: string | null;
  last_error_code: string | null;
  last_error_at: string | null;
  receipt_ref: string | null;
  reconciliation_required: boolean;
  reconciliation_checked_at: string | null;
  correlation_id: string;
}

export interface RedactedAppointmentRow {
  id: string;
  workshop_id: string;
  case_id: string;
  start_at: string;
  end_at: string;
  status: string;
  version: number;
}

// ==========================================
// SUPPLIERS DOMAIN INTERFACES (Workshop & Admin)
// ==========================================

export interface WorkshopSupplierLink {
  id: string;
  supplierName: string;
  accountRef?: string;
  status: 'linked' | 'pending' | 'unlinked';
  isBibendiaPreferred: boolean;
  effectiveDiscountRate?: number;
  deliverySlaHours?: number;
  notes?: string;
}

export interface PlatformSupplierSummary {
  id: string;
  name: string;
  commercialCode: string;
  status: 'active' | 'evaluating' | 'suspended';
  coverageZones: string[];
  isNetworkPreferred: boolean;
  catalogsCount: number;
  linkedWorkshopsCount: number;
  commissionRatePct?: number;
}

// ==========================================
// PLATFORM ADMIN DOMAIN INTERFACES (P0.9)
// ==========================================

export interface PlatformTenantSummary {
  id: string;
  name: string;
  locale: string;
  timezone: string;
  operating_mode: 'standard' | 'pilot_supervised';
  lifecycle_status: 'provisioning' | 'pilot' | 'active' | 'suspended' | 'deactivated';
  kill_switch_enabled: boolean;
  version: number;
  created_at: string;
  updated_at: string;
}

export interface PlatformWorkshopRow {
  id: string;
  tenant_id: string;
  name: string;
  timezone: string;
  opening_hours: Record<string, unknown>;
  status: 'active' | 'suspended' | 'closed';
  version: number;
  updated_at: string;
}

export interface PlatformMembershipRow {
  user_id: string;
  tenant_id: string;
  role: 'OWNER' | 'MANAGER' | 'RECEPTION' | 'VIEWER';
  status: 'active' | 'suspended' | 'revoked';
  valid_from: string;
  valid_until: string | null;
  version: number;
  created_at: string;
  updated_at: string;
}

export interface PlatformGrantRow {
  id: string;
  user_id: string;
  role: 'PLATFORM_ADMIN' | 'PLATFORM_OPERATOR' | 'SUPPORT_READONLY' | 'SECURITY_AUDITOR';
  scope_type: string;
  tenant_id: string;
  status: 'active' | 'suspended' | 'revoked';
  valid_from: string;
  valid_until: string | null;
  version: number;
  created_at: string;
  updated_at: string;
}

export interface PlatformChannelEndpointRow {
  id: string;
  tenant_id: string;
  workshop_id: string;
  provider: 'twilio' | 'vapi' | 'elevenlabs';
  external_account_id: string;
  called_endpoint: string;
  status: 'active' | 'suspended' | 'revoked';
  version: number;
  updated_at: string;
}

export interface PlatformIntegrationRow {
  id: string;
  tenant_id: string;
  workshop_id: string;
  channel_endpoint_id: string;
  status: 'active' | 'suspended' | 'revoked';
  version: number;
  updated_at: string;
  provider: 'twilio' | 'elevenlabs';
  service_type: 'telephony_provider' | 'voice_provider';
  external_account_id: string;
  principal_status: string;
}

export interface PlatformAuditEventRow {
  id: number;
  event_type: string;
  entity_type: string;
  entity_id: string;
  actor_type?: string;
  actor_id?: string;
  correlation_id: string;
  evidence_ref?: string;
  occurred_at: string;
}

