export type NavSection = 
  | 'midia' 
  | 'bandeja' 
  | 'agenda' 
  | 'directorio'
  | 'presupuestos' 
  | 'seguimientos' 
  | 'proveedores'
  | 'impacto' 
  | 'configuracion'
  | 'integraciones';

export interface Vehicle {
  id: string;
  plate: string;
  brand: string;
  model: string;
  year: number;
  kilometers: number;
  motorization: string;
  vin?: string;
  lastServiceDate?: string;
  futureRecommendation?: string;
}

export interface Customer {
  id: string;
  name: string;
  phone: string;
  email: string;
  avatarUrl?: string;
  notes?: string;
}

export interface Message {
  id: string;
  channel: 'whatsapp' | 'phone' | 'web' | 'sms';
  sender: 'client' | 'ai' | 'workshop';
  senderName: string;
  content: string;
  timestamp: string;
}

export interface BibendiaUnderstanding {
  wants: string[];
  alreadyKnows: string[];
  missingInfo: string[];
  nextStep: string;
  autoActionNotice?: string;
  confidence?: 'high' | 'needs_confirmation';
  suggestedSlots?: { date: string; time: string; label: string; workload: string }[];
}

export interface Conversation {
  id: string;
  customerId: string;
  vehicleId: string;
  channel: 'whatsapp' | 'phone' | 'web' | 'sms';
  status: 'needs_attention' | 'ai_handling' | 'resolved';
  unread: boolean;
  lastUpdate: string;
  messages: Message[];
  understanding: BibendiaUnderstanding;
}

export interface Appointment {
  id: string;
  customerId: string;
  vehicleId: string;
  serviceName: string;
  estimatedDurationMinutes: number;
  date: string; // YYYY-MM-DD
  time: string; // HH:mm
  status: 'scheduled' | 'in_progress' | 'completed' | 'sent_to_dms';
  assignedMechanic?: 'Jon' | 'Iker';
  aiCreated: boolean;
  workloadLevel?: 'low' | 'medium' | 'high';
  slotQuality?: 'optimal' | 'good' | 'busy';
  completedNotes?: string;
  futureRecommendation?: string;
}

export type EstimateAutomationStatus = 'AUTO_INCLUDED' | 'REVIEW_REQUIRED' | 'OPTIONAL' | 'BLOCKED';

export interface RepairEvidence {
  source: string;
  reference: string;
  sourceType: string;
  checkedAt: string;
  confidenceState: string;
  reuseStatus: string;
  notes: string | null;
  sourceVersion: string | null;
}

export interface QuoteItem {
  id: string;
  category: 'part' | 'labor';
  description: string;
  quantity: number | null;
  unitPrice: number | null;
  total: number | null;
  currency?: string | null;
  pricingStatus?: 'PENDING' | 'MANUALLY_PRICED';
  automationStatus?: EstimateAutomationStatus;
  reviewRequired?: boolean;
  repairBomEdgeId?: string | null;
  confidenceState?: string;
  evidence?: RepairEvidence[];
  confidenceReason?: string;
  isLocallyModified?: boolean;
  lineSource?: 'REPAIR_KNOWLEDGE' | 'MANUAL_WORKSHOP';
  pricingProvenance?: 'MANUAL_WORKSHOP' | null;
  mutationKey?: string;
  selected?: boolean;
  partRoleCode?: string | null;
  partRoleName?: string | null;
  edgeCode?: string | null;
  itemType?: 'PART_ROLE' | 'CONSUMABLE' | 'LABOR';
}

export interface Quote {
  id: string;
  number: string; // e.g. "PRE-2026-084"
  customerId: string;
  vehicleId: string;
  title: string;
  createdDate: string;
  status: 'draft' | 'pending_approval' | 'sent' | 'accepted' | 'rejected';
  items: QuoteItem[];
  subtotal: number | null;
  tax: number | null; // 21% IVA
  total: number | null;
  estimatedLaborHours: number;
  aiRationale: string;
  uncertaintyWarning?: string;
  customerName?: string;
  vehiclePlate?: string;

  // RK03 / RK04 Technical Draft Provenance & Persistence
  backendDraftId?: string;
  isPersistedBackendDraft?: boolean;
  hasUnsavedLocalChanges?: boolean;
  knowledgeRevision?: string;
  applicabilityCode?: string;
  repairJobCode?: string;
  idempotencyKey?: string;
  version?: number;
  backendDraft?: EstimateDraft;
}

export interface FollowUpOpportunity {
  id: string;
  customerId: string;
  vehicleId: string;
  type: 'unanswered_quote' | 'upcoming_maintenance' | 'recommended_repair' | 'dormant_client';
  title: string;
  description: string;
  daysPending: number;
  potentialValue: number;
  suggestedMessage: string;
  status: 'pending' | 'sent' | 'converted' | 'dismissed';
}

export interface AiImpactLog {
  id: string;
  timestamp: string; // HH:mm or Date string
  title: string;
  details: string;
  category: 'reception' | 'booking' | 'quote' | 'followup' | 'billing';
  timeSavedMinutes: number;
  revenueImpact?: number;
  isRecovery?: boolean; // Only true if generated by follow-up conversion!
}

// ==========================================
// REAL BACKEND CONTRACT INTERFACES (P0.3 / P0.5)
// ==========================================

export type IdentityResolution = 'verified' | 'provisional_new' | 'provisional_ambiguous';

export interface WorkshopAppointmentResponse {
  id: string;
  tenant_id: string;
  workshop_id: string;
  case_id: string | null;
  customer_id: string | null;
  vehicle_id: string | null;
  identity_resolution?: IdentityResolution | string;
  service_request: {
    intent?: string;
    symptoms?: string[];
    notes?: string;
    estimated_duration_minutes?: number;
    [key: string]: unknown;
  };
  start_at: string;
  end_at: string;
  status: string;
  customer_wait_mode?: 'DROP_OFF' | 'WAIT_ON_SITE';
  confirmation_evidence_ref: string | null;
  version: number;
  customer_name: string;
  vehicle_plate: string;
  origin?: 'voice_phone' | 'workshop_manual' | 'web_lead' | 'dms_import' | string;
}

export interface TenantControlResponse {
  lifecycle: 'provisioning' | 'pilot' | 'active' | 'suspended' | 'deactivated';
  lifecycleUpdatedAt: string | null;
  lifecycleUpdatedBy: { type: string; id: string } | null;
  lifecycleReason: string | null;
  killSwitch: {
    enabled: boolean;
    updatedAt: string | null;
    updatedBy: string | null;
    reason: string | null;
  };
  version: number;
}

export interface OutboxSummaryRow {
  delivery_state: string;
  count: number;
  oldest_at: string | null;
  max_attempts: number;
}

export interface OutboxAttentionRow {
  id: string;
  event_type: string;
  aggregate_type: string;
  aggregate_id: string;
  delivery_state: string;
  occurred_at: string;
  attempts: number;
  max_attempts: number;
  next_attempt_at: string | null;
  lease_until: string | null;
  last_error_code: string | null;
  last_error_at: string | null;
  receipt_ref: string | null;
  reconciliation_required: boolean;
  reconciliation_checked_at: string | null;
  correlation_id: string;
}

export interface RedactedAppointmentRow {
  id: string;
  workshop_id: string;
  case_id: string;
  start_at: string;
  end_at: string;
  status: string;
  version: number;
}

// ==========================================
// SUPPLIERS DOMAIN INTERFACES (Workshop & Admin)
// ==========================================

export interface WorkshopSupplierLink {
  id: string;
  supplierName: string;
  accountRef?: string;
  status: 'linked' | 'pending' | 'unlinked';
  isBibendiaPreferred: boolean;
  effectiveDiscountRate?: number;
  deliverySlaHours?: number;
  notes?: string;
}

export interface PlatformSupplierSummary {
  id: string;
  name: string;
  commercialCode: string;
  status: 'active' | 'evaluating' | 'suspended';
  coverageZones: string[];
  isNetworkPreferred: boolean;
  catalogsCount: number;
  linkedWorkshopsCount: number;
  commissionRatePct?: number;
}

// ==========================================
// PLATFORM ADMIN DOMAIN INTERFACES (P0.9)
// ==========================================

export interface PlatformTenantSummary {
  id: string;
  name: string;
  locale: string;
  timezone: string;
  operating_mode: 'standard' | 'pilot_supervised';
  lifecycle_status: 'provisioning' | 'pilot' | 'active' | 'suspended' | 'deactivated';
  kill_switch_enabled: boolean;
  version: number;
  created_at: string;
  updated_at: string;
}

export interface PlatformWorkshopRow {
  id: string;
  tenant_id: string;
  name: string;
  timezone: string;
  opening_hours: Record<string, unknown>;
  status: 'active' | 'suspended' | 'closed';
  version: number;
  updated_at: string;
}

export interface PlatformMembershipRow {
  user_id: string;
  tenant_id: string;
  role: 'OWNER' | 'MANAGER' | 'RECEPTION' | 'VIEWER';
  status: 'active' | 'suspended' | 'revoked';
  valid_from: string;
  valid_until: string | null;
  version: number;
  created_at: string;
  updated_at: string;
}

export interface PlatformGrantRow {
  id: string;
  user_id: string;
  role: 'PLATFORM_ADMIN' | 'PLATFORM_OPERATOR' | 'SUPPORT_READONLY' | 'SECURITY_AUDITOR';
  scope_type: string;
  tenant_id: string;
  status: 'active' | 'suspended' | 'revoked';
  valid_from: string;
  valid_until: string | null;
  version: number;
  created_at: string;
  updated_at: string;
}

export interface PlatformChannelEndpointRow {
  id: string;
  tenant_id: string;
  workshop_id: string;
  provider: 'twilio' | 'vapi' | 'elevenlabs';
  external_account_id: string;
  called_endpoint: string;
  status: 'active' | 'suspended' | 'revoked';
  version: number;
  updated_at: string;
}

export interface PlatformIntegrationRow {
  id: string;
  tenant_id: string;
  workshop_id: string;
  channel_endpoint_id: string;
  status: 'active' | 'suspended' | 'revoked';
  version: number;
  updated_at: string;
  provider: 'twilio' | 'elevenlabs';
  service_type: 'telephony_provider' | 'voice_provider';
  external_account_id: string;
  principal_status: string;
}

export interface PlatformAuditEventRow {
  id: number;
  event_type: string;
  entity_type: string;
  entity_id: string;
  actor_type?: string;
  actor_id?: string;
  correlation_id: string;
  evidence_ref?: string;
  occurred_at: string;
}

// ==========================================
// REPAIR KNOWLEDGE & ESTIMATE DRAFTS (RK03)
// ==========================================

export type ConfidenceState = 
  | 'VERIFIED_OEM'
  | 'VERIFIED_MANUFACTURER'
  | 'MULTI_SOURCE_VERIFIED'
  | 'DERIVED_FROM_KIT'
  | 'COMMUNITY_SUPPORTED'
  | 'INFERRED'
  | 'UNKNOWN';

export type BomClassification = 'EXPLICIT_BOM' | 'DERIVED_FROM_KIT' | 'MULTI_SOURCE_BOM' | 'TECHNICAL_RULE';
export type RequirementType = 'REQUIRED' | 'RECOMMENDED' | 'CONDITIONAL' | 'OPTIONAL';

export interface RepairKnowledgeEdge {
  code: string;
  itemKind: 'PART_ROLE' | 'CONSUMABLE';
  partRole: {
    code: string;
    name: string;
    category: string;
  };
  quantity: number | null;
  requirementType: RequirementType;
  bomClassification: BomClassification;
  confidenceState: ConfidenceState;
  condition: string | null;
  replaceOnce: boolean;
  side: string | null;
  axle: string | null;
  position: string | null;
  notes: string | null;
  automationEligible: boolean;
  manualReviewRequired: boolean;
  confidenceReason: string;
  evidence: RepairEvidence[];
}

export interface RepairKnowledgeResolution {
  applicability: {
    code: string;
    make: string;
    model: string;
    generation: string | null;
    variant: string | null;
    engineCode: string;
    productionFrom: string | null;
    productionTo: string | null;
    restrictions: string | null;
  };
  repairJob: {
    code: string;
    system: string;
    subsystem: string;
    name: string;
    description: string | null;
  };
  components: RepairKnowledgeEdge[];
  consumables: RepairKnowledgeEdge[];
}

export type EstimateDraftStatus = 'technical_draft' | 'pending_approval' | 'sent' | 'approved' | 'superseded';

export interface EstimateDraftLine {
  id: string;
  repairBomEdgeId?: string | null;
  edgeCode?: string | null;
  itemType: 'PART_ROLE' | 'CONSUMABLE' | 'LABOR';
  partRoleCode: string;
  partRoleName: string;
  quantity: number | null;
  requirementType: string;
  replaceOnce: boolean;
  condition: string | null;
  confidenceState: string;
  automationStatus: EstimateAutomationStatus;
  reviewRequired: boolean;
  selected: boolean;
  confidenceReason: string;
  evidence: RepairEvidence[];
  notes: string | null;
  description: string;
  lineSource?: 'REPAIR_KNOWLEDGE' | 'MANUAL_WORKSHOP';
  pricingProvenance?: 'MANUAL_WORKSHOP' | null;
  unitPrice: number | null;
  currency: string | null;
  pricingStatus: 'PENDING' | 'MANUALLY_PRICED';
  editable: true;
}

export interface EstimateDraftSummary {
  id: string;
  vehicleId: string | null;
  customerId?: string | null;
  repairJobCode?: string | null;
  draftType?: 'REPAIR_KNOWLEDGE' | 'MANUAL_WORKSHOP';
  title?: string | null;
  status: EstimateDraftStatus;
  version: number;
  createdAt: string;
  updatedAt: string;
  customerSnapshot?: { name?: string; phone?: string; email?: string } | null;
  vehicleSnapshot?: { plate?: string; make?: string; model?: string; year?: number; vin?: string } | null;
}

export interface EstimateDraft {
  id: string;
  tenantId: string;
  draftType?: 'REPAIR_KNOWLEDGE' | 'MANUAL_WORKSHOP';
  vehicleId: string | null;
  customerId?: string | null;
  appointmentId?: string | null;
  repairJobCode: string | null;
  applicabilityCode: string | null;
  title?: string | null;
  status: EstimateDraftStatus;
  version: number;
  idempotencyKey: string;
  knowledgeRevision: string | null;
  createdAt: string;
  updatedAt?: string;
  customerSnapshot?: { name?: string; phone?: string; email?: string } | null;
  vehicleSnapshot?: { plate?: string; make?: string; model?: string; year?: number; vin?: string } | null;
  operation: {
    code: string;
    name: string;
    description: string | null;
    unitPrice: number | null;
    currency: string | null;
    pricingStatus: 'PENDING' | 'MANUALLY_PRICED';
    editable: true;
  };
  lines: EstimateDraftLine[];
}

export interface CreateManualEstimateDraftCommand {
  kind: 'manual';
  idempotencyKey: string;
  title?: string;
  customerId?: string | null;
  vehicleId?: string | null;
  appointmentId?: string | null;
  customerSnapshot?: {
    name?: string;
    phone?: string;
    email?: string;
  };
  vehicleSnapshot?: {
    plate?: string;
    make?: string;
    model?: string;
    year?: number;
    vin?: string;
  };
  lines?: {
    mutationKey: string;
    description: string;
    itemType: 'PART_ROLE' | 'CONSUMABLE' | 'LABOR';
    quantity: number | null;
    unitPrice: number | null;
    currency: string | null;
    selected?: boolean;
  }[];
}

export interface WorkshopCustomer {
  id: string;
  name: string;
  phone: string | null;
  email: string | null;
  notes: string | null;
  vehicles?: WorkshopVehicle[];
  activitySummary?: {
    appointmentsCount: number;
    estimatesCount: number;
    lastAppointmentAt: string | null;
  };
}

export interface WorkshopVehicle {
  id: string;
  plate: string | null;
  make: string | null;
  model: string | null;
  year: number | null;
  vin: string | null;
  customerId?: string | null;
  customer?: {
    id: string;
    name: string;
    phone?: string | null;
    email?: string | null;
  } | null;
}

export interface WorkshopAppointmentSummary {
  id: string;
  startAt: string;
  endAt: string;
  serviceIntent: string;
  status: string;
  customerWaitMode?: 'DROP_OFF' | 'WAIT_ON_SITE';
  origin?: string;
  vehicleId?: string | null;
  vehiclePlate?: string | null;
  vehicleMake?: string | null;
  vehicleModel?: string | null;
}

export interface WorkshopEstimateSummary {
  id: string;
  title: string | null;
  draftType?: 'REPAIR_KNOWLEDGE' | 'MANUAL_WORKSHOP';
  provenance: 'manual' | 'rk' | 'mixed';
  status: string;
  total: number;
  linesCount?: number;
  createdAt: string;
  updatedAt: string;
  vehicleId?: string | null;
  vehiclePlate?: string | null;
  vehicleMake?: string | null;
  vehicleModel?: string | null;
}

export interface CustomerDetailResponse {
  customer: WorkshopCustomer;
  vehicles: WorkshopVehicle[];
  activity: {
    appointments: WorkshopAppointmentSummary[];
    estimates: WorkshopEstimateSummary[];
  };
}

export interface VehicleDetailResponse {
  vehicle: WorkshopVehicle;
  customer: {
    id: string;
    name: string;
    phone?: string | null;
    email?: string | null;
  } | null;
  customers: Array<{
    id: string;
    name: string;
    phone?: string | null;
    email?: string | null;
    role: string;
  }>;
  activity: {
    appointments: WorkshopAppointmentSummary[];
    estimates: WorkshopEstimateSummary[];
  };
}

export interface CreateWorkshopAppointmentCommand {
  idempotencyKey: string;
  startAt: string;
  endAt?: string;
  durationMinutes: number;
  serviceIntent: string;
  customerWaitMode?: 'DROP_OFF' | 'WAIT_ON_SITE';
  notes?: string;
  customerId?: string | null;
  vehicleId?: string | null;
  customerSnapshot?: {
    name?: string;
    phone?: string;
    email?: string;
  };
  vehicleSnapshot?: {
    plate?: string;
    make?: string;
    model?: string;
    year?: number;
    vin?: string;
  };
}

export interface EstimateLineChange {
  id?: string;
  mutationKey?: string;
  description: string;
  itemType: 'PART_ROLE' | 'CONSUMABLE' | 'LABOR';
  quantity: number | null;
  unitPrice: number | null;
  currency: string | null;
  selected: boolean;
}

export interface EditEstimateDraftCommand {
  expectedVersion: number;
  idempotencyKey: string;
  status?: EstimateDraftStatus;
  lines?: EstimateLineChange[];
  deleteLineIds?: string[];
  customerId?: string | null;
  vehicleId?: string | null;
}

export interface ResolveRepairKnowledgeQuery {
  make: string;
  model: string;
  engineCode?: string;
  repairJobCode: string;
  productionDate?: string;
  variant?: string;
}

export interface CreateEstimateDraftCommand {
  vehicleId: string;
  idempotencyKey: string;
  vehicle: {
    make: string;
    model: string;
    engineCode?: string;
    productionDate?: string;
    variant?: string;
  };
  repairJobCode: string;
}

export * from './vehicleCatalog';
