import { randomUUID } from 'node:crypto';
import type { FastifyInstance } from 'fastify';
import type pg from 'pg';
import { z } from 'zod';
import { inAuthorizedPlatformTransaction } from '../auth/platform-authorization.js';
import { inAuthorizedTenantTransaction } from '../auth/tenant-authorization.js';
import type { Capability, PlatformRole, WorkshopRole } from '../auth/capabilities.js';
import type { PlatformPrincipal } from '../auth/principal.js';

export class PlatformAdminError extends Error {
  constructor(public readonly code: 'VERSION_CONFLICT'|'IDEMPOTENCY_CONFLICT'|'ENTITY_NOT_FOUND') { super(code); }
}

const auth={config:{auth:{mode:'authenticated' as const,audience:'platform' as const,principalKinds:['platform_user'] as const}}};
const uuid=z.string().uuid(); const key=z.string().min(8).max(200);
const page=z.object({limit:z.coerce.number().int().min(1).max(100).default(50),cursor:z.coerce.number().int().positive().optional()}).strict();
const tenantCreate=z.object({name:z.string().trim().min(2).max(160),locale:z.string().min(2).max(20).default('es-ES'),timezone:z.string().min(2).max(80).default('Europe/Madrid'),operatingMode:z.enum(['standard','pilot_supervised']).default('pilot_supervised'),workshop:z.object({name:z.string().trim().min(2).max(160),timezone:z.string().min(2).max(80).default('Europe/Madrid'),openingHours:z.record(z.string(),z.unknown()).default({})}).strict(),idempotencyKey:key}).strict();
const tenantPatch=z.object({name:z.string().trim().min(2).max(160).optional(),locale:z.string().min(2).max(20).optional(),timezone:z.string().min(2).max(80).optional(),operatingMode:z.enum(['standard','pilot_supervised']).optional(),expectedVersion:z.number().int().positive(),idempotencyKey:key}).strict();
const workshopCreate=z.object({name:z.string().trim().min(2).max(160),timezone:z.string().min(2).max(80).default('Europe/Madrid'),openingHours:z.record(z.string(),z.unknown()).default({}),idempotencyKey:key}).strict();
const workshopPatch=z.object({name:z.string().trim().min(2).max(160).optional(),timezone:z.string().min(2).max(80).optional(),openingHours:z.record(z.string(),z.unknown()).optional(),status:z.enum(['active','suspended','closed']).optional(),expectedVersion:z.number().int().positive(),idempotencyKey:key}).strict();
const membershipCreate=z.object({userId:uuid,role:z.enum(['OWNER','MANAGER','RECEPTION','VIEWER']),idempotencyKey:key}).strict();
const membershipPatch=z.object({role:z.enum(['OWNER','MANAGER','RECEPTION','VIEWER']).optional(),status:z.enum(['active','suspended','revoked']),expectedVersion:z.number().int().positive(),idempotencyKey:key}).strict();
const grantCreate=z.object({userId:uuid,role:z.enum(['PLATFORM_ADMIN','PLATFORM_OPERATOR','SUPPORT_READONLY','SECURITY_AUDITOR']),idempotencyKey:key}).strict();
const grantPatch=z.object({role:z.enum(['PLATFORM_ADMIN','PLATFORM_OPERATOR','SUPPORT_READONLY','SECURITY_AUDITOR']).optional(),status:z.enum(['active','suspended','revoked']),expectedVersion:z.number().int().positive(),idempotencyKey:key}).strict();
const endpointCreate=z.object({workshopId:uuid,provider:z.enum(['twilio','vapi','elevenlabs']),externalAccountId:z.string().min(1).max(200),calledEndpoint:z.string().min(1).max(200),idempotencyKey:key}).strict();
const endpointPatch=z.object({status:z.enum(['active','suspended','revoked']),calledEndpoint:z.string().min(1).max(200).optional(),expectedVersion:z.number().int().positive(),idempotencyKey:key}).strict();
const integrationCreate=z.object({workshopId:uuid,channelEndpointId:uuid,provider:z.enum(['twilio','elevenlabs']),serviceType:z.enum(['telephony_provider','voice_provider']),externalAccountId:z.string().min(1).max(200),credentialRef:z.string().min(8).max(500),idempotencyKey:key}).strict();
const integrationPatch=z.object({status:z.enum(['active','suspended','revoked']),credentialRef:z.string().min(8).max(500).optional(),expectedVersion:z.number().int().positive(),idempotencyKey:key}).strict();

export function registerPlatformAdminRoutes(app:FastifyInstance,pool:pg.Pool) {
  app.get('/v1/platform/tenants',auth,async(req)=>{
    const q=page.parse(req.query); const principal=platform(req.principal);
    const data=await inAuthorizedPlatformTransaction(pool,{principal,capability:'platform:tenant:read',correlationId:req.id},async(c,ctx)=>{
      const params:unknown[]=[]; let where='';
      if(!ctx.global){params.push(ctx.tenantIds);where='WHERE id=ANY($1::uuid[])';}
      params.push(q.limit); return (await c.query(`SELECT id,name,locale,timezone,operating_mode,lifecycle_status,kill_switch_enabled,version,created_at,updated_at FROM tenants ${where} ORDER BY created_at,id LIMIT $${params.length}`,params)).rows;
    }); return {data,correlationId:req.id};
  });
  app.post('/v1/platform/tenants',auth,async(req,reply)=>{
    const body=tenantCreate.parse(req.body),principal=platform(req.principal);
    const receipt=await inAuthorizedPlatformTransaction(pool,{principal,capability:'platform:tenant:create',correlationId:req.id,requireGlobal:true},async(c,ctx)=>{
      const replay=await findReceipt(c,ctx.principal.userId,body.idempotencyKey,'tenant.create'); if(replay)return replay;
      const tenant=(await c.query(`INSERT INTO tenants(name,locale,timezone,operating_mode) VALUES($1,$2,$3,$4) RETURNING *`,[body.name,body.locale,body.timezone,body.operatingMode])).rows[0];
      await c.query('SELECT set_config($1,$2,true)',['app.tenant_id',tenant.id]);
      const workshop=(await c.query(`INSERT INTO workshops(tenant_id,name,timezone,opening_hours) VALUES($1,$2,$3,$4) RETURNING id,tenant_id,name,timezone,opening_hours,version`,[tenant.id,body.workshop.name,body.workshop.timezone,body.workshop.openingHours])).rows[0];
      return record(c,{tenantId:tenant.id,operation:'tenant.create',entityType:'tenant',entityId:tenant.id,actorId:ctx.principal.userId,key:body.idempotencyKey,correlationId:req.id,after:{tenant:safeTenant(tenant),workshop}});
    }); return reply.code(201).send({receipt,correlationId:req.id});
  });
  app.get('/v1/platform/tenants/:tenantId',auth,tenantRead(pool));
  app.patch('/v1/platform/tenants/:tenantId',auth,async(req)=> scoped(pool,req,'platform:tenant:update',async(c,tenantId,actor)=>{
    const b=tenantPatch.parse(req.body),replay=await findReceipt(c,actor,b.idempotencyKey,'tenant.update');if(replay)return replay;
    const before=await one(c,'SELECT * FROM tenants WHERE id=$1',[tenantId]);
    const result=await c.query(`UPDATE tenants SET name=COALESCE($2,name),locale=COALESCE($3,locale),timezone=COALESCE($4,timezone),operating_mode=COALESCE($5,operating_mode),version=version+1,updated_at=now() WHERE id=$1 AND version=$6 RETURNING *`,[tenantId,b.name??null,b.locale??null,b.timezone??null,b.operatingMode??null,b.expectedVersion]);
    if(!result.rowCount)throw new PlatformAdminError('VERSION_CONFLICT');
    return record(c,{tenantId,operation:'tenant.update',entityType:'tenant',entityId:tenantId,actorId:actor,key:b.idempotencyKey,correlationId:req.id,before:safeTenant(before),after:safeTenant(result.rows[0])});
  }));

  app.get('/v1/platform/tenants/:tenantId/workshops',auth,list(pool,'platform:configuration:read','SELECT id,tenant_id,name,timezone,opening_hours,status,version,updated_at FROM workshops WHERE tenant_id=$1 ORDER BY name'));
  app.post('/v1/platform/tenants/:tenantId/workshops',auth,async(req,reply)=>{const out=await scoped(pool,req,'platform:configuration:update',async(c,t,a)=>{const b=workshopCreate.parse(req.body),r=await findReceipt(c,a,b.idempotencyKey,'workshop.create');if(r)return r;const row=(await c.query(`INSERT INTO workshops(tenant_id,name,timezone,opening_hours) VALUES($1,$2,$3,$4) RETURNING id,tenant_id,name,timezone,opening_hours,status,version`,[t,b.name,b.timezone,b.openingHours])).rows[0];return record(c,{tenantId:t,operation:'workshop.create',entityType:'workshop',entityId:row.id,actorId:a,key:b.idempotencyKey,correlationId:req.id,after:row});});return reply.code(201).send({receipt:out,correlationId:req.id})});
  app.patch('/v1/platform/tenants/:tenantId/workshops/:entityId',auth,patchSimple(pool,'platform:configuration:update',workshopPatch,'workshops','workshop',`name=COALESCE($3,name),timezone=COALESCE($4,timezone),opening_hours=COALESCE($5,opening_hours),status=COALESCE($6,status)`,(b)=>[b.name??null,b.timezone??null,b.openingHours??null,b.status??null]));

  app.get('/v1/platform/tenants/:tenantId/memberships',auth,list(pool,'platform:memberships:manage',`SELECT user_id,tenant_id,role,status,valid_from,valid_until,version,created_at,updated_at FROM tenant_memberships WHERE tenant_id=$1 ORDER BY created_at`));
  app.post('/v1/platform/tenants/:tenantId/memberships',auth,createMembership(pool));
  app.patch('/v1/platform/tenants/:tenantId/memberships/:entityId',auth,patchMembership(pool));
  app.get('/v1/platform/tenants/:tenantId/grants',auth,list(pool,'platform:memberships:manage',`SELECT id,user_id,role,scope_type,tenant_id,status,valid_from,valid_until,version,created_at,updated_at FROM platform_access_grants WHERE tenant_id=$1 ORDER BY created_at`));
  app.post('/v1/platform/tenants/:tenantId/grants',auth,createGrant(pool));
  app.patch('/v1/platform/tenants/:tenantId/grants/:entityId',auth,patchGrant(pool));

  app.get('/v1/platform/tenants/:tenantId/channel-endpoints',auth,list(pool,'platform:configuration:read',`SELECT id,tenant_id,workshop_id,provider,external_account_id,called_endpoint,status,version,updated_at FROM channel_endpoints WHERE tenant_id=$1 ORDER BY provider,id`));
  app.post('/v1/platform/tenants/:tenantId/channel-endpoints',auth,createEndpoint(pool));
  app.patch('/v1/platform/tenants/:tenantId/channel-endpoints/:entityId',auth,patchSimple(pool,'platform:configuration:update',endpointPatch,'channel_endpoints','channel_endpoint',`status=$3,called_endpoint=COALESCE($4,called_endpoint)`,(b)=>[b.status,b.calledEndpoint??null]));
  app.get('/v1/platform/tenants/:tenantId/integrations',auth,list(pool,'platform:configuration:read',`SELECT b.id,b.tenant_id,b.workshop_id,b.channel_endpoint_id,b.status,b.version,b.updated_at,s.provider,s.service_type,s.external_account_id,s.status AS principal_status FROM provider_bindings b JOIN service_principals s ON s.id=b.service_principal_id WHERE b.tenant_id=$1 ORDER BY s.provider,b.id`));
  app.post('/v1/platform/tenants/:tenantId/integrations',auth,createIntegration(pool));
  app.patch('/v1/platform/tenants/:tenantId/integrations/:entityId',auth,patchIntegration(pool));
  app.get('/v1/platform/tenants/:tenantId/activity',auth,pagedAudit(pool,'platform:activity:read',false));
  app.get('/v1/platform/tenants/:tenantId/audit',auth,pagedAudit(pool,'platform:audit:read',true));
}

function tenantRead(pool:pg.Pool){return async(req:any)=>scoped(pool,req,'platform:tenant:read',async(c,t)=>({data:safeTenant(await one(c,'SELECT * FROM tenants WHERE id=$1',[t])),correlationId:req.id}));}
function list(pool:pg.Pool,cap:Capability,sql:string){return async(req:any)=>scoped(pool,req,cap,async(c,t)=>({data:(await c.query(sql,[t])).rows,correlationId:req.id}));}
async function scoped<T>(pool:pg.Pool,req:any,cap:Capability,fn:(c:pg.PoolClient,t:string,a:string)=>Promise<T>){const t=uuid.parse(req.params.tenantId),p=platform(req.principal);return inAuthorizedTenantTransaction(pool,{principal:p,requestedTenantId:t,capability:cap,correlationId:req.id},(c,x)=>fn(c,t,x.principal.kind==='platform_user'?x.principal.userId:''));}
function platform(p:any):PlatformPrincipal{if(!p||p.kind!=='platform_user')throw new Error('AUTHENTICATION_REQUIRED');return p;}
async function one(c:pg.PoolClient,sql:string,args:unknown[]){const r=await c.query(sql,args);if(!r.rowCount)throw new PlatformAdminError('ENTITY_NOT_FOUND');return r.rows[0];}
function safeTenant(r:any){return {id:r.id,name:r.name,locale:r.locale,timezone:r.timezone,operatingMode:r.operating_mode,lifecycleStatus:r.lifecycle_status,killSwitchEnabled:r.kill_switch_enabled,version:r.version,createdAt:r.created_at,updatedAt:r.updated_at};}
async function findReceipt(c:pg.PoolClient,actor:string,k:string,op:string){const r=await c.query('SELECT * FROM platform_command_receipts WHERE actor_id=$1 AND idempotency_key=$2',[actor,k]);if(!r.rowCount)return null;if(r.rows[0].operation!==op)throw new PlatformAdminError('IDEMPOTENCY_CONFLICT');return receiptShape(r.rows[0]);}
function receiptShape(r:any){return {receiptId:r.id,operation:r.operation,entityType:r.entity_type,entityId:r.entity_id,before:r.before_jsonb,after:r.after_jsonb,correlationId:r.correlation_id,evidenceRef:r.evidence_ref,occurredAt:r.occurred_at};}
async function record(c:pg.PoolClient,x:{tenantId:string;operation:string;entityType:string;entityId:string;actorId:string;key:string;correlationId:string;before?:any;after:any}){const id=randomUUID(),evidence=`postgres:platform-command-receipt:${id}`;const r=(await c.query(`INSERT INTO platform_command_receipts(id,tenant_id,operation,entity_type,entity_id,actor_type,actor_id,idempotency_key,before_jsonb,after_jsonb,correlation_id,evidence_ref) VALUES($1,$2,$3,$4,$5,'platform_user',$6,$7,$8,$9,$10,$11) RETURNING *`,[id,x.tenantId,x.operation,x.entityType,x.entityId,x.actorId,x.key,x.before??null,x.after,x.correlationId,evidence])).rows[0];await c.query(`INSERT INTO audit_events(tenant_id,actor_type,actor_id,event_type,entity_type,entity_id,correlation_id,evidence_ref) VALUES($1,'platform_user',$2,$3,$4,$5,$6,$7)`,[x.tenantId,x.actorId,x.operation,x.entityType,x.entityId,x.correlationId,evidence]);await c.query(`INSERT INTO outbox_events(tenant_id,aggregate_type,aggregate_id,event_type,payload_jsonb,external_idempotency_key,correlation_id) VALUES($1,$2,$3,$4,$5,$6,$7)`,[x.tenantId,x.entityType,uuid.safeParse(x.entityId).success?x.entityId:x.tenantId,x.operation,{entityId:x.entityId,receiptId:id},`platform:${id}`,x.correlationId]);return receiptShape(r);}

function patchSimple(pool:pg.Pool,cap:Capability,schema:any,table:string,type:string,setSql:string,values:(b:any)=>unknown[]){return async(req:any)=>scoped(pool,req,cap,async(c,t,a)=>{const id=uuid.parse(req.params.entityId),b=schema.parse(req.body),op=`${type}.update`,replay=await findReceipt(c,a,b.idempotencyKey,op);if(replay)return {receipt:replay,correlationId:req.id};const before=await one(c,`SELECT * FROM ${table} WHERE tenant_id=$1 AND id=$2`,[t,id]);const args=[t,id,...values(b),b.expectedVersion];const r=await c.query(`UPDATE ${table} SET ${setSql},version=version+1,updated_at=now() WHERE tenant_id=$1 AND id=$2 AND version=$${args.length} RETURNING *`,args);if(!r.rowCount)throw new PlatformAdminError('VERSION_CONFLICT');const receipt=await record(c,{tenantId:t,operation:op,entityType:type,entityId:id,actorId:a,key:b.idempotencyKey,correlationId:req.id,before,after:r.rows[0]});return {receipt,correlationId:req.id};});}
function createMembership(pool:pg.Pool){return async(req:any,reply:any)=>{const out=await scoped(pool,req,'platform:memberships:manage',async(c,t,a)=>{const b=membershipCreate.parse(req.body),r=await findReceipt(c,a,b.idempotencyKey,'membership.create');if(r)return r;const row=(await c.query(`INSERT INTO tenant_memberships(user_id,tenant_id,role) VALUES($1,$2,$3) RETURNING *`,[b.userId,t,b.role as WorkshopRole])).rows[0];return record(c,{tenantId:t,operation:'membership.create',entityType:'membership',entityId:b.userId,actorId:a,key:b.idempotencyKey,correlationId:req.id,after:row});});return reply.code(201).send({receipt:out,correlationId:req.id});};}
function patchMembership(pool:pg.Pool){return async(req:any)=>scoped(pool,req,'platform:memberships:manage',async(c,t,a)=>{const id=uuid.parse(req.params.entityId),b=membershipPatch.parse(req.body),op='membership.update',rr=await findReceipt(c,a,b.idempotencyKey,op);if(rr)return {receipt:rr,correlationId:req.id};const before=await one(c,'SELECT * FROM tenant_memberships WHERE tenant_id=$1 AND user_id=$2',[t,id]);const r=await c.query(`UPDATE tenant_memberships SET role=COALESCE($3,role),status=$4,version=version+1,updated_at=now() WHERE tenant_id=$1 AND user_id=$2 AND version=$5 RETURNING *`,[t,id,b.role??null,b.status,b.expectedVersion]);if(!r.rowCount)throw new PlatformAdminError('VERSION_CONFLICT');return {receipt:await record(c,{tenantId:t,operation:op,entityType:'membership',entityId:id,actorId:a,key:b.idempotencyKey,correlationId:req.id,before,after:r.rows[0]}),correlationId:req.id};});}
function createGrant(pool:pg.Pool){return async(req:any,reply:any)=>{const out=await scoped(pool,req,'platform:memberships:manage',async(c,t,a)=>{const b=grantCreate.parse(req.body),r=await findReceipt(c,a,b.idempotencyKey,'grant.create');if(r)return r;const row=(await c.query(`INSERT INTO platform_access_grants(user_id,role,scope_type,tenant_id) VALUES($1,$2,'tenant',$3) RETURNING *`,[b.userId,b.role as PlatformRole,t])).rows[0];return record(c,{tenantId:t,operation:'grant.create',entityType:'grant',entityId:row.id,actorId:a,key:b.idempotencyKey,correlationId:req.id,after:row});});return reply.code(201).send({receipt:out,correlationId:req.id});};}
function patchGrant(pool:pg.Pool){return async(req:any)=>scoped(pool,req,'platform:memberships:manage',async(c,t,a)=>{const id=uuid.parse(req.params.entityId),b=grantPatch.parse(req.body),op='grant.update',rr=await findReceipt(c,a,b.idempotencyKey,op);if(rr)return {receipt:rr,correlationId:req.id};const before=await one(c,'SELECT * FROM platform_access_grants WHERE tenant_id=$1 AND id=$2',[t,id]);const r=await c.query(`UPDATE platform_access_grants SET role=COALESCE($3,role),status=$4,version=version+1,updated_at=now() WHERE tenant_id=$1 AND id=$2 AND version=$5 RETURNING *`,[t,id,b.role??null,b.status,b.expectedVersion]);if(!r.rowCount)throw new PlatformAdminError('VERSION_CONFLICT');return {receipt:await record(c,{tenantId:t,operation:op,entityType:'grant',entityId:id,actorId:a,key:b.idempotencyKey,correlationId:req.id,before,after:r.rows[0]}),correlationId:req.id};});}
function createEndpoint(pool:pg.Pool){return async(req:any,reply:any)=>{const out=await scoped(pool,req,'platform:configuration:update',async(c,t,a)=>{const b=endpointCreate.parse(req.body),rr=await findReceipt(c,a,b.idempotencyKey,'channel_endpoint.create');if(rr)return rr;const row=(await c.query(`INSERT INTO channel_endpoints(tenant_id,workshop_id,provider,external_account_id,called_endpoint) VALUES($1,$2,$3,$4,$5) RETURNING *`,[t,b.workshopId,b.provider,b.externalAccountId,b.calledEndpoint])).rows[0];return record(c,{tenantId:t,operation:'channel_endpoint.create',entityType:'channel_endpoint',entityId:row.id,actorId:a,key:b.idempotencyKey,correlationId:req.id,after:row});});return reply.code(201).send({receipt:out,correlationId:req.id});};}
function createIntegration(pool:pg.Pool){return async(req:any,reply:any)=>{const out=await scoped(pool,req,'platform:configuration:update',async(c,t,a)=>{const b=integrationCreate.parse(req.body),rr=await findReceipt(c,a,b.idempotencyKey,'integration.create');if(rr)return rr;const sp=(await c.query(`INSERT INTO service_principals(provider,service_type,external_account_id,credential_ref) VALUES($1,$2,$3,$4) RETURNING id,provider,service_type,external_account_id,status`,[b.provider,b.serviceType,b.externalAccountId,b.credentialRef])).rows[0];const row=(await c.query(`INSERT INTO provider_bindings(service_principal_id,tenant_id,workshop_id,channel_endpoint_id) VALUES($1,$2,$3,$4) RETURNING *`,[sp.id,t,b.workshopId,b.channelEndpointId])).rows[0];return record(c,{tenantId:t,operation:'integration.create',entityType:'integration',entityId:row.id,actorId:a,key:b.idempotencyKey,correlationId:req.id,after:{...row,provider:sp.provider,serviceType:sp.service_type,externalAccountId:sp.external_account_id}});});return reply.code(201).send({receipt:out,correlationId:req.id});};}
function patchIntegration(pool:pg.Pool){return async(req:any)=>scoped(pool,req,'platform:configuration:update',async(c,t,a)=>{const id=uuid.parse(req.params.entityId),b=integrationPatch.parse(req.body),op='integration.update',rr=await findReceipt(c,a,b.idempotencyKey,op);if(rr)return {receipt:rr,correlationId:req.id};const before=await one(c,`SELECT b.*,s.provider,s.service_type,s.external_account_id FROM provider_bindings b JOIN service_principals s ON s.id=b.service_principal_id WHERE b.tenant_id=$1 AND b.id=$2`,[t,id]);if(b.credentialRef)await c.query('UPDATE service_principals SET credential_ref=$1,updated_at=now() WHERE id=$2',[b.credentialRef,before.service_principal_id]);const r=await c.query(`UPDATE provider_bindings SET status=$3,version=version+1,updated_at=now() WHERE tenant_id=$1 AND id=$2 AND version=$4 RETURNING *`,[t,id,b.status,b.expectedVersion]);if(!r.rowCount)throw new PlatformAdminError('VERSION_CONFLICT');const after={...r.rows[0],provider:before.provider,serviceType:before.service_type,externalAccountId:before.external_account_id,credentialRotated:Boolean(b.credentialRef)};return {receipt:await record(c,{tenantId:t,operation:op,entityType:'integration',entityId:id,actorId:a,key:b.idempotencyKey,correlationId:req.id,before:{...before,credential_ref:undefined},after}),correlationId:req.id};});}
function pagedAudit(pool:pg.Pool,cap:Capability,full:boolean){return async(req:any)=>{const q=page.parse(req.query);return scoped(pool,req,cap,async(c,t)=>{const args:any[]=[t];let cursor='';if(q.cursor){args.push(q.cursor);cursor=`AND id<$${args.length}`;}args.push(q.limit);const cols=full?'id,event_type,entity_type,entity_id,actor_type,actor_id,correlation_id,evidence_ref,occurred_at':'id,event_type,entity_type,entity_id,correlation_id,occurred_at';const data=(await c.query(`SELECT ${cols} FROM audit_events WHERE tenant_id=$1 ${cursor} ORDER BY id DESC LIMIT $${args.length}`,args)).rows;return {data,nextCursor:data.length===q.limit?data[data.length-1].id:null,redacted:true,correlationId:req.id};});};}
