import { randomUUID } from 'node:crypto';
import { afterAll,beforeAll,describe,expect,it } from 'vitest';
import type { AuthenticationAdapter } from '../../src/auth/authentication-adapter.js';
import type { PrincipalContext } from '../../src/auth/principal.js';
import { buildApi } from '../../src/api/app.js';
import { createPool } from '../../src/persistence/pool.js';

const pool=createPool('migrator');
const ids={admin:randomUUID(),operator:randomUUID(),support:randomUUID(),member:randomUUID(),foreign:randomUUID(),tenantB:randomUUID()};
const future=new Date(Date.now()+3600_000).toISOString(),authenticatedAt=new Date().toISOString();
const principal=(userId:string):PrincipalContext=>({kind:'platform_user',audience:'platform',userId,issuer:'test',subject:userId,sessionId:randomUUID(),authenticatedAt,expiresAt:future,assurance:'mfa'});
const tokens=new Map([['Bearer admin',principal(ids.admin)],['Bearer operator',principal(ids.operator)],['Bearer support',principal(ids.support)],['Bearer foreign',principal(ids.foreign)]]);
const authentication:AuthenticationAdapter={async authenticate(r){return r.authorization?tokens.get(r.authorization)??null:null}};
const app=buildApi(pool,{authentication}); let tenantId='',workshopId='',endpointId='',integrationId='';
const send=(method:'GET'|'POST'|'PATCH',url:string,token:string,payload?:Record<string,unknown>)=>app.inject({method,url,headers:{authorization:token,'x-tenant-id':ids.tenantB},payload});

beforeAll(async()=>{await pool.query('RESET ROLE');await pool.query(`INSERT INTO users(id,status) VALUES ($1,'active'),($2,'active'),($3,'active'),($4,'active'),($5,'active')`,Object.values(ids).slice(0,5));await pool.query(`INSERT INTO platform_access_grants(user_id,role,scope_type) VALUES($1,'PLATFORM_ADMIN','global')`,[ids.admin]);await pool.query(`INSERT INTO tenants(id,name,lifecycle_status) VALUES($1,'Foreign tenant','pilot')`,[ids.tenantB]);await pool.query(`INSERT INTO platform_access_grants(user_id,role,scope_type,tenant_id) VALUES($1,'SUPPORT_READONLY','tenant',$2)`,[ids.foreign,ids.tenantB]);await app.ready();});
afterAll(async()=>{await app.close();await pool.query('RESET ROLE');if(tenantId)await pool.query('DELETE FROM outbox_events WHERE tenant_id=$1',[tenantId]);if(tenantId)await pool.query('DELETE FROM audit_events WHERE tenant_id=$1',[tenantId]);if(tenantId)await pool.query('DELETE FROM platform_command_receipts WHERE tenant_id=$1',[tenantId]);if(tenantId)await pool.query('DELETE FROM provider_bindings WHERE tenant_id=$1',[tenantId]);await pool.query(`DELETE FROM service_principals WHERE external_account_id='acct-jarrisons-test'`);if(tenantId)await pool.query('DELETE FROM channel_endpoints WHERE tenant_id=$1',[tenantId]);if(tenantId)await pool.query('DELETE FROM tenant_memberships WHERE tenant_id=$1',[tenantId]);if(tenantId)await pool.query('DELETE FROM platform_access_grants WHERE tenant_id=$1',[tenantId]);if(tenantId)await pool.query('DELETE FROM workshops WHERE tenant_id=$1',[tenantId]);if(tenantId)await pool.query('DELETE FROM tenants WHERE id=$1',[tenantId]);await pool.query('DELETE FROM platform_access_grants WHERE user_id=ANY($1::uuid[])',[Object.values(ids).slice(0,5)]);await pool.query('DELETE FROM users WHERE id=ANY($1::uuid[])',[Object.values(ids).slice(0,5)]);await pool.query('DELETE FROM tenants WHERE id=$1',[ids.tenantB]);await pool.end();});

describe('P0.9 no-SQL Jarrisons operation',()=>{
  it('provisions tenant+workshop transactionally and replays idempotently',async()=>{const body={name:'Jarrisons',workshop:{name:'Jarrisons Bilbao'},idempotencyKey:'jarrisons-create-001'};const first=await send('POST','/v1/platform/tenants','Bearer admin',body);expect(first.statusCode).toBe(201);tenantId=first.json().receipt.entityId;workshopId=first.json().receipt.after.workshop.id;const replay=await send('POST','/v1/platform/tenants','Bearer admin',body);expect(replay.statusCode).toBe(201);expect(replay.json().receipt.receiptId).toBe(first.json().receipt.receiptId);expect((await pool.query('SELECT count(*)::int n FROM tenants WHERE name=$1',['Jarrisons'])).rows[0].n).toBe(1);});
  it('derives closed roles, denies insufficient roles and ignores x-tenant-id authority',async()=>{await pool.query(`INSERT INTO platform_access_grants(user_id,role,scope_type,tenant_id) VALUES($1,'PLATFORM_OPERATOR','tenant',$3),($2,'SUPPORT_READONLY','tenant',$3)`,[ids.operator,ids.support,tenantId]);expect((await send('GET',`/v1/platform/tenants/${tenantId}`,'Bearer support')).statusCode).toBe(200);expect((await send('POST',`/v1/platform/tenants/${tenantId}/memberships`,'Bearer operator',{userId:ids.member,role:'OWNER',idempotencyKey:'membership-denied-001'})).statusCode).toBe(403);expect((await send('GET',`/v1/platform/tenants/${ids.tenantB}`,'Bearer support')).statusCode).toBe(403);const added=await send('POST',`/v1/platform/tenants/${tenantId}/memberships`,'Bearer admin',{userId:ids.member,role:'OWNER',idempotencyKey:'membership-create-001'});expect(added.statusCode).toBe(201);expect(added.body).not.toContain('capabilities');});
  it('enforces optimistic concurrency and writes receipt/audit/outbox atomically',async()=>{const ok=await send('PATCH',`/v1/platform/tenants/${tenantId}`,'Bearer admin',{name:'Jarrisons Motor',expectedVersion:1,idempotencyKey:'tenant-update-001'});expect(ok.statusCode).toBe(200);const conflict=await send('PATCH',`/v1/platform/tenants/${tenantId}`,'Bearer admin',{name:'stale',expectedVersion:1,idempotencyKey:'tenant-update-002'});expect(conflict.statusCode).toBe(409);const counts=await pool.query(`SELECT (SELECT count(*) FROM platform_command_receipts WHERE tenant_id=$1) receipts,(SELECT count(*) FROM audit_events WHERE tenant_id=$1 AND event_type='tenant.update') audits,(SELECT count(*) FROM outbox_events WHERE tenant_id=$1 AND event_type='tenant.update') outbox`,[tenantId]);expect(counts.rows[0]).toMatchObject({audits:'1',outbox:'1'});});
  it('configures channels and integrations without returning credential references',async()=>{const ep=await send('POST',`/v1/platform/tenants/${tenantId}/channel-endpoints`,'Bearer operator',{workshopId,provider:'elevenlabs',externalAccountId:'agent-jarrisons-test',calledEndpoint:'agent-jarrisons-test',idempotencyKey:'endpoint-create-001'});expect(ep.statusCode).toBe(201);endpointId=ep.json().receipt.entityId;const integration=await send('POST',`/v1/platform/tenants/${tenantId}/integrations`,'Bearer operator',{workshopId,channelEndpointId:endpointId,provider:'elevenlabs',serviceType:'voice_provider',externalAccountId:'acct-jarrisons-test',credentialRef:'vault://jarrisons/elevenlabs',idempotencyKey:'integration-create-001'});expect(integration.statusCode).toBe(201);integrationId=integration.json().receipt.entityId;expect(integration.body).not.toContain('vault://');expect(integration.body).not.toContain('credential');const listed=await send('GET',`/v1/platform/tenants/${tenantId}/integrations`,'Bearer support');expect(listed.statusCode).toBe(200);expect(listed.body).not.toContain('credential');});
  it('supports grants lifecycle and safe paginated activity/audit',async()=>{const grant=await send('POST',`/v1/platform/tenants/${tenantId}/grants`,'Bearer admin',{userId:ids.foreign,role:'SUPPORT_READONLY',idempotencyKey:'grant-create-001'});expect(grant.statusCode).toBe(201);const grantId=grant.json().receipt.entityId;const suspended=await send('PATCH',`/v1/platform/tenants/${tenantId}/grants/${grantId}`,'Bearer admin',{status:'suspended',expectedVersion:1,idempotencyKey:'grant-suspend-001'});expect(suspended.statusCode).toBe(200);expect((await send('GET',`/v1/platform/tenants/${tenantId}/activity?limit=2`,'Bearer support')).statusCode).toBe(200);expect((await send('GET',`/v1/platform/tenants/${tenantId}/audit?limit=2`,'Bearer admin')).statusCode).toBe(200);});
  it('keeps FORCE RLS and safe persistence invariants',async()=>{const force=await pool.query(`SELECT relname,relforcerowsecurity FROM pg_class WHERE relname=ANY($1::text[]) ORDER BY relname`,[['tenants','workshops','tenant_memberships','platform_access_grants','channel_endpoints','provider_bindings','platform_command_receipts']]);expect(force.rows.every((r)=>r.relforcerowsecurity)).toBe(true);const stored=await pool.query(`SELECT credential_ref FROM service_principals WHERE external_account_id='acct-jarrisons-test'`);expect(stored.rows[0].credential_ref).toBe('vault://jarrisons/elevenlabs');expect(JSON.stringify((await pool.query('SELECT before_jsonb,after_jsonb FROM platform_command_receipts WHERE tenant_id=$1',[tenantId])).rows)).not.toContain('vault://');});
});
