import { randomUUID } from 'node:crypto';
import { afterAll,beforeAll,beforeEach,describe,expect,it } from 'vitest';
import { AesGcmPiiProtection } from '../../src/security/pii-protection.js';
import { buildApi } from '../../src/api/app.js';
import { createPool } from '../../src/persistence/pool.js';
import { PublicLeadNotificationAdapter,SmtpDeliveryError,type SmtpMessage,type SmtpTransport } from '../../src/adapters/smtp/public-lead-smtp.js';
import { claimOutboxBatch,dispatchClaimedOutboxEvent } from '../../src/worker/outbox.js';

const pool=createPool('migrator'),tenant=randomUUID(),other=randomUUID();const key=Buffer.alloc(32,7),pii=new AesGcmPiiProtection(new Map([['k',key]]),'k',new Map([['h',key]]),'h');
const app=buildApi(pool,{piiProtection:pii,publicLead:{tenantId:tenant,rateLimit:20,dedupeMinutes:15,retentionDays:365}});
const valid={workshop:'Taller Norte',contactName:'Ane López',phone:'+34 600 123 456',email:'ane@example.com',message:'Necesito información',website:''};
beforeAll(async()=>{await pool.query("INSERT INTO tenants(id,name,lifecycle_status) VALUES($1,'Public acquisition','pilot'),($2,'Other','pilot')",[tenant,other]);await app.ready();});
beforeEach(async()=>{await pool.query('DELETE FROM outbox_events WHERE tenant_id=$1',[tenant]);await pool.query('DELETE FROM audit_events WHERE tenant_id=$1',[tenant]);await pool.query('DELETE FROM public_leads WHERE tenant_id=$1',[tenant]);await pool.query('DELETE FROM public_lead_rate_limits WHERE tenant_id=$1',[tenant]);});
afterAll(async()=>{await app.close();await pool.query('DELETE FROM outbox_events WHERE tenant_id=$1',[tenant]);await pool.query('DELETE FROM audit_events WHERE tenant_id=$1',[tenant]);await pool.query('DELETE FROM public_leads WHERE tenant_id=$1',[tenant]);await pool.query('DELETE FROM public_lead_rate_limits WHERE tenant_id=$1',[tenant]);await pool.query('DELETE FROM tenants WHERE id=ANY($1::uuid[])',[[tenant,other]]);await pool.end();});
const post=(body:Record<string,unknown>,headers:Record<string,string>={})=>app.inject({method:'POST',url:'/public/leads',payload:body,headers:{'content-type':'application/json',...headers}});

describe('public lead acquisition',()=>{
 it('persists a valid encrypted Lead + Audit + Outbox atomically under server tenant authority',async()=>{const r=await post({...valid,tenantId:other});expect(r.statusCode).toBe(400);const ok=await post(valid,{'idempotency-key':'browser-request-001'});expect(ok.statusCode).toBe(202);expect(ok.body).not.toContain('Ane');expect(ok.body).not.toContain('600');expect(ok.body).not.toContain('example.com');const rows=await pool.query(`SELECT l.tenant_id,l.workshop_ciphertext,l.retention_until,a.event_type,o.event_type outbox_type,o.payload_jsonb FROM public_leads l JOIN audit_events a ON a.tenant_id=l.tenant_id AND a.entity_id=l.id::text JOIN outbox_events o ON o.tenant_id=l.tenant_id AND o.aggregate_id=l.id WHERE l.tenant_id=$1`,[tenant]);expect(rows.rows).toHaveLength(1);expect(rows.rows[0]).toMatchObject({tenant_id:tenant,event_type:'public_lead.received',outbox_type:'public_lead.notification_requested'});expect(rows.rows[0].payload_jsonb).toEqual({leadId:expect.any(String)});expect(Buffer.from(rows.rows[0].workshop_ciphertext).toString()).not.toContain('Taller Norte');});
 it('strictly rejects malformed/unknown/non-JSON and oversized requests',async()=>{expect((await post({...valid,extra:true})).statusCode).toBe(400);expect((await post({...valid,email:'bad'})).statusCode).toBe(400);expect((await post({...valid,phone:'123'})).statusCode).toBe(400);expect((await app.inject({method:'POST',url:'/public/leads',payload:'x',headers:{'content-type':'text/plain'}})).statusCode).toBe(415);expect((await post({...valid,message:'x'.repeat(17000)})).statusCode).toBe(413);expect((await pool.query('SELECT count(*)::int n FROM public_leads WHERE tenant_id=$1',[tenant])).rows[0].n).toBe(0);});
 it('silently absorbs honeypot submissions without persistence',async()=>{const r=await post({...valid,website:'https://spam.invalid'});expect(r.statusCode).toBe(202);expect((await pool.query('SELECT count(*)::int n FROM public_leads WHERE tenant_id=$1',[tenant])).rows[0].n).toBe(0);});
 it('separates technical retry from temporal human deduplication',async()=>{const a=await post(valid,{'idempotency-key':'same-request-001'}),b=await post(valid,{'idempotency-key':'same-request-001'}),c=await post(valid,{'idempotency-key':'different-request-002'});expect([a.statusCode,b.statusCode,c.statusCode]).toEqual([202,202,202]);expect((await pool.query('SELECT count(*)::int n FROM public_leads WHERE tenant_id=$1',[tenant])).rows[0].n).toBe(1);expect((await pool.query('SELECT count(*)::int n FROM outbox_events WHERE tenant_id=$1',[tenant])).rows[0].n).toBe(1);});
 it('rolls back all authoritative records when acquisition tenant is unavailable',async()=>{await pool.query("UPDATE tenants SET lifecycle_status='suspended' WHERE id=$1",[tenant]);expect((await post(valid)).statusCode).toBe(503);expect((await pool.query('SELECT count(*)::int n FROM public_leads WHERE tenant_id=$1',[tenant])).rows[0].n).toBe(0);await pool.query("UPDATE tenants SET lifecycle_status='pilot' WHERE id=$1",[tenant]);});
 it('rolls back the Lead when a later Audit write fails',async()=>{await pool.query(`CREATE OR REPLACE FUNCTION reject_test_lead_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.tenant_id='${tenant}'::uuid AND NEW.event_type='public_lead.received' THEN RAISE EXCEPTION 'injected audit failure'; END IF; RETURN NEW; END $$`);await pool.query('CREATE TRIGGER reject_test_lead_audit BEFORE INSERT ON audit_events FOR EACH ROW EXECUTE FUNCTION reject_test_lead_audit()');try{expect((await post(valid)).statusCode).toBe(500);expect((await pool.query('SELECT count(*)::int n FROM public_leads WHERE tenant_id=$1',[tenant])).rows[0].n).toBe(0);expect((await pool.query('SELECT count(*)::int n FROM outbox_events WHERE tenant_id=$1',[tenant])).rows[0].n).toBe(0);}finally{await pool.query('DROP TRIGGER reject_test_lead_audit ON audit_events');await pool.query('DROP FUNCTION reject_test_lead_audit()');}});
 it('enforces tenant RLS for the public lead table',async()=>{await post(valid);const client=await pool.connect();try{await client.query('BEGIN');await client.query('SET LOCAL ROLE bibendia_api');await client.query("SELECT set_config('app.tenant_id',$1,true)",[other]);expect((await client.query('SELECT * FROM public_leads')).rows).toHaveLength(0);await client.query('ROLLBACK');}finally{client.release();}});
 it('renders an escaped SMTP notification through a controlled adapter',async()=>{await post({...valid,message:'<script>alert(1)</script>'});const event=(await pool.query(`SELECT *,gen_random_uuid() lease_token,'test' lease_owner FROM outbox_events WHERE tenant_id=$1`,[tenant])).rows[0];let sent:SmtpMessage|undefined;const transport:SmtpTransport={async send(m){sent=m;return {receiptRef:'smtp:test-receipt'}}};const adapter=new PublicLeadNotificationAdapter(pool,pii,transport,'no-reply@bibendia.com','info@bibendia.com');expect(await adapter.execute(event,event.external_idempotency_key,new AbortController().signal)).toMatchObject({outcome:'succeeded'});expect(sent).toMatchObject({to:'info@bibendia.com',replyTo:'ane@example.com'});expect(sent!.html).toContain('&lt;script&gt;');expect(sent!.html).not.toContain('<script>');});
 it('keeps the Lead and applies Outbox retry/permanent classifications for SMTP failures',async()=>{await post(valid);let claimed=(await claimOutboxBatch(pool,tenant,1,'smtp-test'))[0];const transient=new PublicLeadNotificationAdapter(pool,pii,{async send(){throw new SmtpDeliveryError('transient','SMTP_TEMPORARY_FAILURE')}},'no-reply@bibendia.com','info@bibendia.com');expect(await dispatchClaimedOutboxEvent(pool,tenant,claimed.id,claimed.lease_token,transient)).toBe('failed_safe_to_retry');await pool.query("UPDATE outbox_events SET next_attempt_at=now()-interval '1 second' WHERE id=$1",[claimed.id]);claimed=(await claimOutboxBatch(pool,tenant,1,'smtp-test'))[0];const permanent=new PublicLeadNotificationAdapter(pool,pii,{async send(){throw new SmtpDeliveryError('permanent','SMTP_REJECTED')}},'no-reply@bibendia.com','info@bibendia.com');expect(await dispatchClaimedOutboxEvent(pool,tenant,claimed.id,claimed.lease_token,permanent)).toBe('dead_letter');expect((await pool.query('SELECT count(*)::int n FROM public_leads WHERE tenant_id=$1',[tenant])).rows[0].n).toBe(1);});
});
